/** Colours offered for categories; chosen to stay readable on white and as chart bars. */
export const CATEGORY_COLORS = [
  '#1baf7a',
  '#0f9d8a',
  '#2a78d6',
  '#3f51b5',
  '#6d5bd0',
  '#8e44ad',
  '#c2185b',
  '#d9534f',
  '#e8743b',
  '#e0a100',
  '#00838f',
  '#546e7a',
];

/** Material icons offered for categories. */
export const CATEGORY_ICONS = [
  'payments',
  'savings',
  'work',
  'home_work',
  'card_giftcard',
  'trending_up',
  'shopping_cart',
  'home',
  'receipt_long',
  'bolt',
  'water_drop',
  'wifi',
  'phone_iphone',
  'directions_car',
  'local_gas_station',
  'directions_bus',
  'restaurant',
  'local_cafe',
  'medical_services',
  'fitness_center',
  'movie',
  'sports_esports',
  'subscriptions',
  'checkroom',
  'school',
  'child_care',
  'pets',
  'redeem',
  'flight',
  'build',
  'account_balance',
  'more_horiz',
];
